export const LOGIN_USER_STARTED = 'LOGIN_USER_STARTED'
export const LOGIN_USER_SECCEEDED = 'LOGIN_USER_SECCEEDED'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'

export const LOGOUT_USER= 'LOGOUT_USER'
