export const LOGIN_USER_STARTED = 'LOGIN_USER_STARTED'
export const LOGIN_USER_SECCEEDED = 'LOGIN_USER_SECCEEDED'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'

export const LOGOUT_USER_STARTED = 'LOGOUT_USER_STARTED'
export const LOGOUT_USER_SECCEEDED = 'LOGOUT_USER_SECCEEDED'
export const LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED'
